### ISSUE TITLE
Index default view needs to be Latest

### ISSUE THREAD

**Issue by theindexla** [theindex-la/theindex.la-www#16]
Currently, the Index is not defaulted to latest. Needs to reflect latest order in CMS.

**Comment by kitajchuk** [comment]
@theindexla I have a feeler out to the prismic folks about this one. My expectation is that the content should come out of the CMS in order of creation date from newest to oldest but this does not seem to be the case. I'll let you know what I find out about this. The data documents don't even have a timestamp on them so we cannot even sort them ourselves once we have them.

**Comment by kitajchuk** [comment]
Is this still the case?

**Comment by theindexla** [comment]
It seems to be working now! yaaaassss
