### ISSUE TITLE
add in ability to multi-select: Category, Location, Type

### ISSUE THREAD

**Issue by theindexla** [theindex-la/theindex.la-www#19]

**Comment by kitajchuk** [comment]
@theindexla Is this all or one? For instance, if I choose 2 categories should the index only show artists with BOTH of those categories or should it show artists with either of those categories?

**Comment by theindexla** [comment]
BOTH

so for example if I click Film and Photography, I'm only seeing artists who
do both.

**Comment by kitajchuk** [comment]
Cool. This makes the tool narrow in really quick. But also, we need to handle the scenario in which there are no artists that match the criteria...

**Comment by kitajchuk** [comment]
This is implemented up on staging - staging.theindex.la
