### ISSUE TITLE
main index view | long artist names, force a break

### ISSUE THREAD

**Issue by theindexla** [theindex-la/theindex.la-www#21]
see screenshot below: 

![screen shot 2016-07-23 at 7 42 43 pm](https://cloud.githubusercontent.com/assets/20481365/17090713/ede978ca-51e7-11e6-9be3-9752d3ffaff3.png)

**Comment by kitajchuk** [comment]
This seems fixed now. This is our longest artist name currently, we did some responsive work on artist details the other night - http://staging.theindex.la/artist/nicholas-cope-and-dustin-arnold/

**Comment by theindexla** [comment]
boom! slaying it.
