### ISSUE TITLE
search | after searching and clicking into an artist, search stops working

### ISSUE THREAD

**Issue by theindexla** [theindex-la/theindex.la-www#29]
search: Hannah
click on: Hannah Sider
press back
search: Tara 

No results come back. No message appears. Search appears blank.
![screen shot 2016-08-02 at 2 56 36 pm](https://cloud.githubusercontent.com/assets/20481365/17346814/593a7b62-58c1-11e6-8649-5ae1ebcbf190.png)

**Comment by kitajchuk** [comment]
Ha! This is a funny one :P
