### ISSUE TITLE
social metadata image + copy not pulling in

### ISSUE THREAD

**Issue by theindexla** [theindex-la/theindex.la-www#60]
![screen shot 2016-08-27 at 3 21 41 pm](https://cloud.githubusercontent.com/assets/20481365/18030406/f9a9086e-6c69-11e6-8b8b-ddd96c5ac611.png)

**Comment by kitajchuk** [comment]
This is the tool we can use for this:

https://developers.facebook.com/tools/debug/

**Comment by kitajchuk** [comment]
This was a cache issue. I busted it so should be working now.

<img width="551" alt="screen shot 2016-08-27 at 10 59 44 pm" src="https://cloud.githubusercontent.com/assets/438711/18031941/0f87baf0-6caa-11e6-9524-4a7ed9e3d96b.png">
